AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Example template for lambda function
Resources:
  CalculateStudentGrade:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: calculate-student-grade
      CodeUri: dist
      Handler: app.handler
      Runtime: nodejs12.x
      Timeout: 10
      MemorySize: 128
